# ============================================
# SessionTrackerCP - config
# Author: AllF1RE
# Thx for usage
# Im from Russia, therefore some lines do not 
# contain translation into your language
# I love and respect everyone <3
# ============================================

config-version: 2

# Session settings
session:
  timeout-seconds: 1800

# Cheks settings
checks:
  radius: 60
  time-window-seconds: 10800

# Violation Commands
violation-commands:
  enabled: false
  cooldown-seconds: 120
  commands:
    - "asConsole! broadcast &c[!] &6{player} &7попытался загриферить &c{victim}"
    - "asConsole! log {player} attempted grief on {victim} at {x},{y},{z}"
    - "asConsole! lp user {player} parent add temp.greifer"
    - "asPlayer! msg {player} &cУ тебя {warns} предупреждений!"
    - "asPlayer! title {player} title &cНарушение!"
    - "asPlayer! msg {victim} &aИгрок {player} пытался сломать твой блок!"

# Максимальное количество предупреждений
max-warns:
  default: 10
  permission: "stcp.maxwarns."

# Команды при достижении максимальных предупреждений
max-warns-commands:
  enabled: true
  cooldown-seconds: 300
  commands:
    - "asConsole! broadcast &c[!] &6{player} &7достиг &c{maxwarns} &7предупреждений и был наказан!"
    - "asConsole! tempban {player} 1h Превышение лимита предупреждений"
    - "asPlayer! msg {player} &cТы получил бан на 1 час за {maxwarns} предупреждений!"

# Право обхода проверок
bypass-permission: "stcp.bypass"

# Staff notification settings
staff-notifications:
  default-enabled: false
  permission: "sessiontracker.staff"
  format:
    - "&m----------------------------------------"
    - "&c[!] &6Обнаружено нарушение!"
    - "&eНарушитель: &f{player}"
    - "&eЖертва: &f{victim}"
    - "&eТип: &f{cause}"
    - "&eКоординаты: &f{x}, {y}, {z}"
    - "&m----------------------------------------"

# Soft check for similar names
soft-check:
  enabled: true
  similarity-threshold: 0.75
  reduce-radius: true
  new-radius: 20
  extend-time-window: true
  new-time-window-seconds: 21600

# Logging xD
logging:
  enabled: true
  log-file: "violations"
  format: "! {player} {cause} {uuid} {ip} {x},{y},{z} {reason}"
